#
# Copyright (C) 2024 Antonino Scordino
# Copyright (C) 2024 Souhrud Reddy
#
# SPDX-License-Identifier: Apache-2.0
#

name: Start/Restart Selfhosted Runner
on:
  workflow_dispatch:

jobs:
  run-devspace-and-tmux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

      # Install 'tmux'
    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y tmux

      # Start 'runner' in 'tmux'.
    - name: Run crave devspace
      run: |
          tmux new-session -d -s ghactions 
          tmux send-keys -t ghactions './actions-runner/run.sh' Enter 
          echo "Runner Started""
