name: Vince RiceDroid old
on:
  workflow_dispatch
  
concurrency:
  group: ${{  github.ref }}
  cancel-in-progress: true

jobs:
  Repo_git:
    runs-on: self-hosted
    steps:
      - name: Setup git and install repo
        run: |
          git config --global user.email "rom-builder@rest.eu.org"
          git config --global user.name "ROM BUILDER"
          git config --global pull.rebase true  
          sudo apt-get update -y && sudo apt-get install repo -y
          
  depends:
    runs-on: self-hosted
    steps:
      - name: Install required dependencies
        run: sudo apt-get install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev lib32ncurses5-dev libncurses5 libncurses5-dev -y

  Setup_source:
    runs-on: self-hosted
    needs: [Repo_git]
    steps:
      - name: Setup source
        run: git-lfs install; repo init --git-lfs --depth=1 --no-repo-verify -u https://github.com/Project-PixelStar/manifest -b 14-qpr3 -g default,-mips,-darwin,-notdefault || echo "Already done"

  Clone_Local_Manifests:
    runs-on: self-hosted
    needs: [Setup_source]
    steps:
      - name: Clone local manifests
        run: git clone https://github.com/Trijal08/local_manifests -b PixelStar_OS-shusky --depth=1 .repo/local_manifests || echo "Already done"

  Sync_source:
    runs-on: self-hosted
    needs: Clone_Local_Manifests
    steps:
      - name: Delete existing builds folders
        run: rm -rf out/target/product/* || echo "Doesn't exist"
        
      - name: Sync source
        run: repo sync -c --no-clone-bundle --force-remove-dirty --optimized-fetch --prune --force-sync -j8
        
  Build_ROM:
    runs-on: self-hosted
    needs: [Sync_source, depends]
    steps:
      - name: Build Vanilla
        run: source build/envsetup.sh; breakfast husky; brunch husky | tee log.log
     
  Release:
    runs-on: self-hosted
    needs: [Build_ROM]
    steps:
        - name: Prepare tag
          id: tag_code
          run: echo "TAG=$(date +'v%d-%m-%Y-%H%M%S')" >> $GITHUB_OUTPUT
          
        - name: Upload modules to release
          uses: svenstaro/upload-release-action@v2
          with:
            repo_token: ${{ secrets.RELEASE_TOKEN }}
            repo_name: rom-builder/Vince-RiceDroid
            tag: ${{ steps.tag_code.outputs.TAG }}
            release_name: ${{ steps.tag_code.outputs.TAG }}
            file_glob: true
            file: out/target/product/*/*husky*.zip
